### ISSUE TITLE
Add Go Docs

### ISSUE THREAD

**Issue by cpurta** [cpurta/tatanka#4]
In order to bring more people into the project and have them understand how the internals of the project
works it would be great to have a majority of the code documented. Let's add the golang doc to all functions
and interfaces so that it is easy to understand what they do. Make sure that it can show up in the godoc.org
so that it is public.﻿

Files needing documentation:

- [x] extensions/exchanges/gdax/exchange.go

- [x] internal/cassandra/cassandra_client.go
- [x] internal/cassandra/client.go

- [x] internal/command/backfill.go
- [x] internal/command/balance.go
- [x] internal/command/list_selectors.go
- [x] internal/command/list_strategies.go
- [x] internal/command/sim.go
- [x] internal/command/trade.go

- [x] internal/config/config.go

- [x] internal/exchanges/exchange_map.go

- [x] internal/factories/period_factory.go

**Comment by ibraimgm** [comment]
I can help with this, but I might need some guidance along the way.

**Comment by spinales** [comment]
I say the same :)

**Comment by cpurta** [comment]
@ibraimgm, @DeathWofl  I can definitely help with guidance along the way. The project is in it's infancy still so it is still being roughed out. I'll update this issue with the files that I think will good to start with and will be the most stable throughout the next few months.

**Comment by iennae** [comment]
https://pkg.go.dev/mod/github.com/cpurta/tatanka@v0.0.0-20200930204740-b30ffff05d1e

**Comment by cpurta** [comment]
Issue description has just been updated with files that need documentation.

**Comment by spinales** [comment]
@cpurta Hi, I'm a bit new to open source, could you give me a hand on how I should do the documentation.

**Comment by cpurta** [comment]
@DeathWofl no worries. If you haven't forked the project yet you'll want to do that. Then create a new branch called `add-go-docs`. You can then begin adding the documentation in the source code. Here is a great article on how to document go source code: https://blog.golang.org/godoc. 

Once you have made the changes you can commit and push those to your fork. Then open a Pull Request from your fork branch to the master branch on this project. Let me know if you need any help along the way. I will also be adding some documentation to the the files in the `model` directory sometime today. I'll link that PR to this issue so that you can reference what adding docs looks like. 

Cheers

**Comment by ibraimgm** [comment]
@DeathWofl to avoid two people doing the exact same work, lets split the files between us. How about you start with the first 6 files and I pick off the rest?

**Comment by spinales** [comment]
@ibraimgm sounds good.
@cpurta Thanks

**Comment by ibraimgm** [comment]
@cpurta done, check #5 for details.

BTW, I you also need to add the hacktoberfest topic to the repository itself.

**Comment by cpurta** [comment]
@ibraimgm just added that topic to the project. Thanks for reminding me!

**Comment by cpurta** [comment]
Resolved with #5 and #6 

@ibraimgm @DeathWofl thanks again for you help with this!
